// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_Mat_exit45_pro.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_Mat_exit45_pro::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_Mat_exit45_pro::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> Block_Mat_exit45_pro::ap_ST_fsm_state1 = "1";
const sc_lv<32> Block_Mat_exit45_pro::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Block_Mat_exit45_pro::ap_const_boolean_1 = true;

Block_Mat_exit45_pro::Block_Mat_exit45_pro(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_b_low_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( b_low_out_full_n );

    SC_METHOD(thread_b_low_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( b_low );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_b_low_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_b_up_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_b_up_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( b_up );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_b_up_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_cols_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols_out_full_n );

    SC_METHOD(thread_cols_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_cols_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_g_low_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( g_low_out_full_n );

    SC_METHOD(thread_g_low_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( g_low );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_g_low_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_g_up_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( g_up_out_full_n );

    SC_METHOD(thread_g_up_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( g_up );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_g_up_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_img_1_cols_V_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_1_cols_V_out_full_n );

    SC_METHOD(thread_img_1_cols_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_img_1_cols_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_img_1_rows_V_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_1_rows_V_out_full_n );

    SC_METHOD(thread_img_1_rows_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_img_1_rows_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_r_low_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r_low_out_full_n );

    SC_METHOD(thread_r_low_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r_low );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_r_low_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_r_up_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r_up_out_full_n );

    SC_METHOD(thread_r_up_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( r_up );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_r_up_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_rows_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );

    SC_METHOD(thread_rows_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_rows_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_out_full_n );
    sensitive << ( cols_out_full_n );
    sensitive << ( img_1_rows_V_out_full_n );
    sensitive << ( img_1_cols_V_out_full_n );
    sensitive << ( r_low_out_full_n );
    sensitive << ( r_up_out_full_n );
    sensitive << ( g_low_out_full_n );
    sensitive << ( g_up_out_full_n );
    sensitive << ( b_low_out_full_n );
    sensitive << ( b_up_out_full_n );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_return_0_preg = "00000000000000000000000000000000";
    ap_return_1_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_Mat_exit45_pro_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, r_low, "(port)r_low");
    sc_trace(mVcdFile, r_up, "(port)r_up");
    sc_trace(mVcdFile, g_low, "(port)g_low");
    sc_trace(mVcdFile, g_up, "(port)g_up");
    sc_trace(mVcdFile, b_low, "(port)b_low");
    sc_trace(mVcdFile, b_up, "(port)b_up");
    sc_trace(mVcdFile, rows_out_din, "(port)rows_out_din");
    sc_trace(mVcdFile, rows_out_full_n, "(port)rows_out_full_n");
    sc_trace(mVcdFile, rows_out_write, "(port)rows_out_write");
    sc_trace(mVcdFile, cols_out_din, "(port)cols_out_din");
    sc_trace(mVcdFile, cols_out_full_n, "(port)cols_out_full_n");
    sc_trace(mVcdFile, cols_out_write, "(port)cols_out_write");
    sc_trace(mVcdFile, img_1_rows_V_out_din, "(port)img_1_rows_V_out_din");
    sc_trace(mVcdFile, img_1_rows_V_out_full_n, "(port)img_1_rows_V_out_full_n");
    sc_trace(mVcdFile, img_1_rows_V_out_write, "(port)img_1_rows_V_out_write");
    sc_trace(mVcdFile, img_1_cols_V_out_din, "(port)img_1_cols_V_out_din");
    sc_trace(mVcdFile, img_1_cols_V_out_full_n, "(port)img_1_cols_V_out_full_n");
    sc_trace(mVcdFile, img_1_cols_V_out_write, "(port)img_1_cols_V_out_write");
    sc_trace(mVcdFile, r_low_out_din, "(port)r_low_out_din");
    sc_trace(mVcdFile, r_low_out_full_n, "(port)r_low_out_full_n");
    sc_trace(mVcdFile, r_low_out_write, "(port)r_low_out_write");
    sc_trace(mVcdFile, r_up_out_din, "(port)r_up_out_din");
    sc_trace(mVcdFile, r_up_out_full_n, "(port)r_up_out_full_n");
    sc_trace(mVcdFile, r_up_out_write, "(port)r_up_out_write");
    sc_trace(mVcdFile, g_low_out_din, "(port)g_low_out_din");
    sc_trace(mVcdFile, g_low_out_full_n, "(port)g_low_out_full_n");
    sc_trace(mVcdFile, g_low_out_write, "(port)g_low_out_write");
    sc_trace(mVcdFile, g_up_out_din, "(port)g_up_out_din");
    sc_trace(mVcdFile, g_up_out_full_n, "(port)g_up_out_full_n");
    sc_trace(mVcdFile, g_up_out_write, "(port)g_up_out_write");
    sc_trace(mVcdFile, b_low_out_din, "(port)b_low_out_din");
    sc_trace(mVcdFile, b_low_out_full_n, "(port)b_low_out_full_n");
    sc_trace(mVcdFile, b_low_out_write, "(port)b_low_out_write");
    sc_trace(mVcdFile, b_up_out_din, "(port)b_up_out_din");
    sc_trace(mVcdFile, b_up_out_full_n, "(port)b_up_out_full_n");
    sc_trace(mVcdFile, b_up_out_write, "(port)b_up_out_write");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, rows_out_blk_n, "rows_out_blk_n");
    sc_trace(mVcdFile, cols_out_blk_n, "cols_out_blk_n");
    sc_trace(mVcdFile, img_1_rows_V_out_blk_n, "img_1_rows_V_out_blk_n");
    sc_trace(mVcdFile, img_1_cols_V_out_blk_n, "img_1_cols_V_out_blk_n");
    sc_trace(mVcdFile, r_low_out_blk_n, "r_low_out_blk_n");
    sc_trace(mVcdFile, r_up_out_blk_n, "r_up_out_blk_n");
    sc_trace(mVcdFile, g_low_out_blk_n, "g_low_out_blk_n");
    sc_trace(mVcdFile, g_up_out_blk_n, "g_up_out_blk_n");
    sc_trace(mVcdFile, b_low_out_blk_n, "b_low_out_blk_n");
    sc_trace(mVcdFile, b_up_out_blk_n, "b_up_out_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Block_Mat_exit45_pro::~Block_Mat_exit45_pro() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void Block_Mat_exit45_pro::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
            ap_return_0_preg = rows.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
            ap_return_1_preg = cols.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void Block_Mat_exit45_pro::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_Mat_exit45_pro::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read()));
}

void Block_Mat_exit45_pro::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_Mat_exit45_pro::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void Block_Mat_exit45_pro::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        ap_return_0 = rows.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void Block_Mat_exit45_pro::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        ap_return_1 = cols.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void Block_Mat_exit45_pro::thread_b_low_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        b_low_out_blk_n = b_low_out_full_n.read();
    } else {
        b_low_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_b_low_out_din() {
    b_low_out_din = b_low.read();
}

void Block_Mat_exit45_pro::thread_b_low_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        b_low_out_write = ap_const_logic_1;
    } else {
        b_low_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_b_up_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        b_up_out_blk_n = b_up_out_full_n.read();
    } else {
        b_up_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_b_up_out_din() {
    b_up_out_din = b_up.read();
}

void Block_Mat_exit45_pro::thread_b_up_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        b_up_out_write = ap_const_logic_1;
    } else {
        b_up_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_cols_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        cols_out_blk_n = cols_out_full_n.read();
    } else {
        cols_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_cols_out_din() {
    cols_out_din = cols.read();
}

void Block_Mat_exit45_pro::thread_cols_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        cols_out_write = ap_const_logic_1;
    } else {
        cols_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_g_low_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        g_low_out_blk_n = g_low_out_full_n.read();
    } else {
        g_low_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_g_low_out_din() {
    g_low_out_din = g_low.read();
}

void Block_Mat_exit45_pro::thread_g_low_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        g_low_out_write = ap_const_logic_1;
    } else {
        g_low_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_g_up_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        g_up_out_blk_n = g_up_out_full_n.read();
    } else {
        g_up_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_g_up_out_din() {
    g_up_out_din = g_up.read();
}

void Block_Mat_exit45_pro::thread_g_up_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        g_up_out_write = ap_const_logic_1;
    } else {
        g_up_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_img_1_cols_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_1_cols_V_out_blk_n = img_1_cols_V_out_full_n.read();
    } else {
        img_1_cols_V_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_img_1_cols_V_out_din() {
    img_1_cols_V_out_din = cols.read();
}

void Block_Mat_exit45_pro::thread_img_1_cols_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        img_1_cols_V_out_write = ap_const_logic_1;
    } else {
        img_1_cols_V_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_img_1_rows_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_1_rows_V_out_blk_n = img_1_rows_V_out_full_n.read();
    } else {
        img_1_rows_V_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_img_1_rows_V_out_din() {
    img_1_rows_V_out_din = rows.read();
}

void Block_Mat_exit45_pro::thread_img_1_rows_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        img_1_rows_V_out_write = ap_const_logic_1;
    } else {
        img_1_rows_V_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_r_low_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        r_low_out_blk_n = r_low_out_full_n.read();
    } else {
        r_low_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_r_low_out_din() {
    r_low_out_din = r_low.read();
}

void Block_Mat_exit45_pro::thread_r_low_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        r_low_out_write = ap_const_logic_1;
    } else {
        r_low_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_r_up_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        r_up_out_blk_n = r_up_out_full_n.read();
    } else {
        r_up_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_r_up_out_din() {
    r_up_out_din = r_up.read();
}

void Block_Mat_exit45_pro::thread_r_up_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        r_up_out_write = ap_const_logic_1;
    } else {
        r_up_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void Block_Mat_exit45_pro::thread_rows_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        rows_out_blk_n = rows_out_full_n.read();
    } else {
        rows_out_blk_n = ap_const_logic_1;
    }
}

void Block_Mat_exit45_pro::thread_rows_out_din() {
    rows_out_din = rows.read();
}

void Block_Mat_exit45_pro::thread_rows_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, rows_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, cols_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, r_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, g_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_low_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, b_up_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_1_cols_V_out_full_n.read())))) {
        rows_out_write = ap_const_logic_1;
    } else {
        rows_out_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_start_out() {
    start_out = real_start.read();
}

void Block_Mat_exit45_pro::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void Block_Mat_exit45_pro::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

