// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fire.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int fire::C_S_AXI_DATA_WIDTH = "100000";
const int fire::C_S_AXI_WSTRB_WIDTH = "100";
const int fire::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic fire::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<24> fire::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> fire::ap_const_lv3_0 = "000";
const sc_lv<1> fire::ap_const_lv1_0 = "0";
const sc_logic fire::ap_const_logic_0 = sc_dt::Log_0;
const bool fire::ap_const_boolean_1 = true;

fire::fire(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fire_AXILiteS_s_axi_U = new fire_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("fire_AXILiteS_s_axi_U");
    fire_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    fire_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    fire_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    fire_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    fire_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    fire_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    fire_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    fire_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    fire_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    fire_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    fire_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    fire_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    fire_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    fire_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    fire_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    fire_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    fire_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    fire_AXILiteS_s_axi_U->ACLK(ap_clk);
    fire_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    fire_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    fire_AXILiteS_s_axi_U->rows(rows);
    fire_AXILiteS_s_axi_U->cols(cols);
    fire_AXILiteS_s_axi_U->r_low(r_low);
    fire_AXILiteS_s_axi_U->r_up(r_up);
    fire_AXILiteS_s_axi_U->g_low(g_low);
    fire_AXILiteS_s_axi_U->g_up(g_up);
    fire_AXILiteS_s_axi_U->b_low(b_low);
    fire_AXILiteS_s_axi_U->b_up(b_up);
    Block_Mat_exit45_pro_U0 = new Block_Mat_exit45_pro("Block_Mat_exit45_pro_U0");
    Block_Mat_exit45_pro_U0->ap_clk(ap_clk);
    Block_Mat_exit45_pro_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit45_pro_U0->ap_start(Block_Mat_exit45_pro_U0_ap_start);
    Block_Mat_exit45_pro_U0->start_full_n(Block_Mat_exit45_pro_U0_start_full_n);
    Block_Mat_exit45_pro_U0->ap_done(Block_Mat_exit45_pro_U0_ap_done);
    Block_Mat_exit45_pro_U0->ap_continue(Block_Mat_exit45_pro_U0_ap_continue);
    Block_Mat_exit45_pro_U0->ap_idle(Block_Mat_exit45_pro_U0_ap_idle);
    Block_Mat_exit45_pro_U0->ap_ready(Block_Mat_exit45_pro_U0_ap_ready);
    Block_Mat_exit45_pro_U0->start_out(Block_Mat_exit45_pro_U0_start_out);
    Block_Mat_exit45_pro_U0->start_write(Block_Mat_exit45_pro_U0_start_write);
    Block_Mat_exit45_pro_U0->rows(rows);
    Block_Mat_exit45_pro_U0->cols(cols);
    Block_Mat_exit45_pro_U0->r_low(r_low);
    Block_Mat_exit45_pro_U0->r_up(r_up);
    Block_Mat_exit45_pro_U0->g_low(g_low);
    Block_Mat_exit45_pro_U0->g_up(g_up);
    Block_Mat_exit45_pro_U0->b_low(b_low);
    Block_Mat_exit45_pro_U0->b_up(b_up);
    Block_Mat_exit45_pro_U0->rows_out_din(Block_Mat_exit45_pro_U0_rows_out_din);
    Block_Mat_exit45_pro_U0->rows_out_full_n(rows_c_full_n);
    Block_Mat_exit45_pro_U0->rows_out_write(Block_Mat_exit45_pro_U0_rows_out_write);
    Block_Mat_exit45_pro_U0->cols_out_din(Block_Mat_exit45_pro_U0_cols_out_din);
    Block_Mat_exit45_pro_U0->cols_out_full_n(cols_c_full_n);
    Block_Mat_exit45_pro_U0->cols_out_write(Block_Mat_exit45_pro_U0_cols_out_write);
    Block_Mat_exit45_pro_U0->img_1_rows_V_out_din(Block_Mat_exit45_pro_U0_img_1_rows_V_out_din);
    Block_Mat_exit45_pro_U0->img_1_rows_V_out_full_n(img_1_rows_V_c_full_n);
    Block_Mat_exit45_pro_U0->img_1_rows_V_out_write(Block_Mat_exit45_pro_U0_img_1_rows_V_out_write);
    Block_Mat_exit45_pro_U0->img_1_cols_V_out_din(Block_Mat_exit45_pro_U0_img_1_cols_V_out_din);
    Block_Mat_exit45_pro_U0->img_1_cols_V_out_full_n(img_1_cols_V_c_full_n);
    Block_Mat_exit45_pro_U0->img_1_cols_V_out_write(Block_Mat_exit45_pro_U0_img_1_cols_V_out_write);
    Block_Mat_exit45_pro_U0->r_low_out_din(Block_Mat_exit45_pro_U0_r_low_out_din);
    Block_Mat_exit45_pro_U0->r_low_out_full_n(r_low_c_full_n);
    Block_Mat_exit45_pro_U0->r_low_out_write(Block_Mat_exit45_pro_U0_r_low_out_write);
    Block_Mat_exit45_pro_U0->r_up_out_din(Block_Mat_exit45_pro_U0_r_up_out_din);
    Block_Mat_exit45_pro_U0->r_up_out_full_n(r_up_c_full_n);
    Block_Mat_exit45_pro_U0->r_up_out_write(Block_Mat_exit45_pro_U0_r_up_out_write);
    Block_Mat_exit45_pro_U0->g_low_out_din(Block_Mat_exit45_pro_U0_g_low_out_din);
    Block_Mat_exit45_pro_U0->g_low_out_full_n(g_low_c_full_n);
    Block_Mat_exit45_pro_U0->g_low_out_write(Block_Mat_exit45_pro_U0_g_low_out_write);
    Block_Mat_exit45_pro_U0->g_up_out_din(Block_Mat_exit45_pro_U0_g_up_out_din);
    Block_Mat_exit45_pro_U0->g_up_out_full_n(g_up_c_full_n);
    Block_Mat_exit45_pro_U0->g_up_out_write(Block_Mat_exit45_pro_U0_g_up_out_write);
    Block_Mat_exit45_pro_U0->b_low_out_din(Block_Mat_exit45_pro_U0_b_low_out_din);
    Block_Mat_exit45_pro_U0->b_low_out_full_n(b_low_c_full_n);
    Block_Mat_exit45_pro_U0->b_low_out_write(Block_Mat_exit45_pro_U0_b_low_out_write);
    Block_Mat_exit45_pro_U0->b_up_out_din(Block_Mat_exit45_pro_U0_b_up_out_din);
    Block_Mat_exit45_pro_U0->b_up_out_full_n(b_up_c_full_n);
    Block_Mat_exit45_pro_U0->b_up_out_write(Block_Mat_exit45_pro_U0_b_up_out_write);
    Block_Mat_exit45_pro_U0->ap_return_0(Block_Mat_exit45_pro_U0_ap_return_0);
    Block_Mat_exit45_pro_U0->ap_return_1(Block_Mat_exit45_pro_U0_ap_return_1);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->input_r_TDATA(input_r_TDATA);
    AXIvideo2Mat_U0->input_r_TVALID(input_r_TVALID);
    AXIvideo2Mat_U0->input_r_TREADY(AXIvideo2Mat_U0_input_r_TREADY);
    AXIvideo2Mat_U0->input_r_TKEEP(input_r_TKEEP);
    AXIvideo2Mat_U0->input_r_TSTRB(input_r_TSTRB);
    AXIvideo2Mat_U0->input_r_TUSER(input_r_TUSER);
    AXIvideo2Mat_U0->input_r_TLAST(input_r_TLAST);
    AXIvideo2Mat_U0->input_r_TID(input_r_TID);
    AXIvideo2Mat_U0->input_r_TDEST(input_r_TDEST);
    AXIvideo2Mat_U0->img_rows_V_read(img_0_rows_V_channel_dout);
    AXIvideo2Mat_U0->img_cols_V_read(img_0_cols_V_channel_dout);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(img_0_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(img_0_data_stream_1_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(img_0_data_stream_2_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    hls_fire_dection_U0 = new hls_fire_dection("hls_fire_dection_U0");
    hls_fire_dection_U0->ap_clk(ap_clk);
    hls_fire_dection_U0->ap_rst(ap_rst_n_inv);
    hls_fire_dection_U0->ap_start(hls_fire_dection_U0_ap_start);
    hls_fire_dection_U0->ap_done(hls_fire_dection_U0_ap_done);
    hls_fire_dection_U0->ap_continue(hls_fire_dection_U0_ap_continue);
    hls_fire_dection_U0->ap_idle(hls_fire_dection_U0_ap_idle);
    hls_fire_dection_U0->ap_ready(hls_fire_dection_U0_ap_ready);
    hls_fire_dection_U0->src_data_stream_0_V_dout(img_0_data_stream_0_dout);
    hls_fire_dection_U0->src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n);
    hls_fire_dection_U0->src_data_stream_0_V_read(hls_fire_dection_U0_src_data_stream_0_V_read);
    hls_fire_dection_U0->src_data_stream_1_V_dout(img_0_data_stream_1_dout);
    hls_fire_dection_U0->src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n);
    hls_fire_dection_U0->src_data_stream_1_V_read(hls_fire_dection_U0_src_data_stream_1_V_read);
    hls_fire_dection_U0->src_data_stream_2_V_dout(img_0_data_stream_2_dout);
    hls_fire_dection_U0->src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n);
    hls_fire_dection_U0->src_data_stream_2_V_read(hls_fire_dection_U0_src_data_stream_2_V_read);
    hls_fire_dection_U0->dst_data_stream_0_V_din(hls_fire_dection_U0_dst_data_stream_0_V_din);
    hls_fire_dection_U0->dst_data_stream_0_V_full_n(img_1_data_stream_0_full_n);
    hls_fire_dection_U0->dst_data_stream_0_V_write(hls_fire_dection_U0_dst_data_stream_0_V_write);
    hls_fire_dection_U0->dst_data_stream_1_V_din(hls_fire_dection_U0_dst_data_stream_1_V_din);
    hls_fire_dection_U0->dst_data_stream_1_V_full_n(img_1_data_stream_1_full_n);
    hls_fire_dection_U0->dst_data_stream_1_V_write(hls_fire_dection_U0_dst_data_stream_1_V_write);
    hls_fire_dection_U0->dst_data_stream_2_V_din(hls_fire_dection_U0_dst_data_stream_2_V_din);
    hls_fire_dection_U0->dst_data_stream_2_V_full_n(img_1_data_stream_2_full_n);
    hls_fire_dection_U0->dst_data_stream_2_V_write(hls_fire_dection_U0_dst_data_stream_2_V_write);
    hls_fire_dection_U0->rows_dout(rows_c_dout);
    hls_fire_dection_U0->rows_empty_n(rows_c_empty_n);
    hls_fire_dection_U0->rows_read(hls_fire_dection_U0_rows_read);
    hls_fire_dection_U0->cols_dout(cols_c_dout);
    hls_fire_dection_U0->cols_empty_n(cols_c_empty_n);
    hls_fire_dection_U0->cols_read(hls_fire_dection_U0_cols_read);
    hls_fire_dection_U0->r_low_dout(r_low_c_dout);
    hls_fire_dection_U0->r_low_empty_n(r_low_c_empty_n);
    hls_fire_dection_U0->r_low_read(hls_fire_dection_U0_r_low_read);
    hls_fire_dection_U0->r_up_dout(r_up_c_dout);
    hls_fire_dection_U0->r_up_empty_n(r_up_c_empty_n);
    hls_fire_dection_U0->r_up_read(hls_fire_dection_U0_r_up_read);
    hls_fire_dection_U0->g_low_dout(g_low_c_dout);
    hls_fire_dection_U0->g_low_empty_n(g_low_c_empty_n);
    hls_fire_dection_U0->g_low_read(hls_fire_dection_U0_g_low_read);
    hls_fire_dection_U0->g_up_dout(g_up_c_dout);
    hls_fire_dection_U0->g_up_empty_n(g_up_c_empty_n);
    hls_fire_dection_U0->g_up_read(hls_fire_dection_U0_g_up_read);
    hls_fire_dection_U0->b_low_dout(b_low_c_dout);
    hls_fire_dection_U0->b_low_empty_n(b_low_c_empty_n);
    hls_fire_dection_U0->b_low_read(hls_fire_dection_U0_b_low_read);
    hls_fire_dection_U0->b_up_dout(b_up_c_dout);
    hls_fire_dection_U0->b_up_empty_n(b_up_c_empty_n);
    hls_fire_dection_U0->b_up_read(hls_fire_dection_U0_b_up_read);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_rows_V_dout(img_1_rows_V_c_dout);
    Mat2AXIvideo_U0->img_rows_V_empty_n(img_1_rows_V_c_empty_n);
    Mat2AXIvideo_U0->img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read);
    Mat2AXIvideo_U0->img_cols_V_dout(img_1_cols_V_c_dout);
    Mat2AXIvideo_U0->img_cols_V_empty_n(img_1_cols_V_c_empty_n);
    Mat2AXIvideo_U0->img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(img_1_data_stream_0_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(img_1_data_stream_0_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(img_1_data_stream_1_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(img_1_data_stream_1_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(img_1_data_stream_2_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(img_1_data_stream_2_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->output_r_TDATA(Mat2AXIvideo_U0_output_r_TDATA);
    Mat2AXIvideo_U0->output_r_TVALID(Mat2AXIvideo_U0_output_r_TVALID);
    Mat2AXIvideo_U0->output_r_TREADY(output_r_TREADY);
    Mat2AXIvideo_U0->output_r_TKEEP(Mat2AXIvideo_U0_output_r_TKEEP);
    Mat2AXIvideo_U0->output_r_TSTRB(Mat2AXIvideo_U0_output_r_TSTRB);
    Mat2AXIvideo_U0->output_r_TUSER(Mat2AXIvideo_U0_output_r_TUSER);
    Mat2AXIvideo_U0->output_r_TLAST(Mat2AXIvideo_U0_output_r_TLAST);
    Mat2AXIvideo_U0->output_r_TID(Mat2AXIvideo_U0_output_r_TID);
    Mat2AXIvideo_U0->output_r_TDEST(Mat2AXIvideo_U0_output_r_TDEST);
    rows_c_U = new fifo_w32_d3_A("rows_c_U");
    rows_c_U->clk(ap_clk);
    rows_c_U->reset(ap_rst_n_inv);
    rows_c_U->if_read_ce(ap_var_for_const0);
    rows_c_U->if_write_ce(ap_var_for_const0);
    rows_c_U->if_din(Block_Mat_exit45_pro_U0_rows_out_din);
    rows_c_U->if_full_n(rows_c_full_n);
    rows_c_U->if_write(Block_Mat_exit45_pro_U0_rows_out_write);
    rows_c_U->if_dout(rows_c_dout);
    rows_c_U->if_empty_n(rows_c_empty_n);
    rows_c_U->if_read(hls_fire_dection_U0_rows_read);
    cols_c_U = new fifo_w32_d3_A("cols_c_U");
    cols_c_U->clk(ap_clk);
    cols_c_U->reset(ap_rst_n_inv);
    cols_c_U->if_read_ce(ap_var_for_const0);
    cols_c_U->if_write_ce(ap_var_for_const0);
    cols_c_U->if_din(Block_Mat_exit45_pro_U0_cols_out_din);
    cols_c_U->if_full_n(cols_c_full_n);
    cols_c_U->if_write(Block_Mat_exit45_pro_U0_cols_out_write);
    cols_c_U->if_dout(cols_c_dout);
    cols_c_U->if_empty_n(cols_c_empty_n);
    cols_c_U->if_read(hls_fire_dection_U0_cols_read);
    img_1_rows_V_c_U = new fifo_w32_d4_A("img_1_rows_V_c_U");
    img_1_rows_V_c_U->clk(ap_clk);
    img_1_rows_V_c_U->reset(ap_rst_n_inv);
    img_1_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_din(Block_Mat_exit45_pro_U0_img_1_rows_V_out_din);
    img_1_rows_V_c_U->if_full_n(img_1_rows_V_c_full_n);
    img_1_rows_V_c_U->if_write(Block_Mat_exit45_pro_U0_img_1_rows_V_out_write);
    img_1_rows_V_c_U->if_dout(img_1_rows_V_c_dout);
    img_1_rows_V_c_U->if_empty_n(img_1_rows_V_c_empty_n);
    img_1_rows_V_c_U->if_read(Mat2AXIvideo_U0_img_rows_V_read);
    img_1_cols_V_c_U = new fifo_w32_d4_A("img_1_cols_V_c_U");
    img_1_cols_V_c_U->clk(ap_clk);
    img_1_cols_V_c_U->reset(ap_rst_n_inv);
    img_1_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_din(Block_Mat_exit45_pro_U0_img_1_cols_V_out_din);
    img_1_cols_V_c_U->if_full_n(img_1_cols_V_c_full_n);
    img_1_cols_V_c_U->if_write(Block_Mat_exit45_pro_U0_img_1_cols_V_out_write);
    img_1_cols_V_c_U->if_dout(img_1_cols_V_c_dout);
    img_1_cols_V_c_U->if_empty_n(img_1_cols_V_c_empty_n);
    img_1_cols_V_c_U->if_read(Mat2AXIvideo_U0_img_cols_V_read);
    r_low_c_U = new fifo_w32_d3_A("r_low_c_U");
    r_low_c_U->clk(ap_clk);
    r_low_c_U->reset(ap_rst_n_inv);
    r_low_c_U->if_read_ce(ap_var_for_const0);
    r_low_c_U->if_write_ce(ap_var_for_const0);
    r_low_c_U->if_din(Block_Mat_exit45_pro_U0_r_low_out_din);
    r_low_c_U->if_full_n(r_low_c_full_n);
    r_low_c_U->if_write(Block_Mat_exit45_pro_U0_r_low_out_write);
    r_low_c_U->if_dout(r_low_c_dout);
    r_low_c_U->if_empty_n(r_low_c_empty_n);
    r_low_c_U->if_read(hls_fire_dection_U0_r_low_read);
    r_up_c_U = new fifo_w32_d3_A("r_up_c_U");
    r_up_c_U->clk(ap_clk);
    r_up_c_U->reset(ap_rst_n_inv);
    r_up_c_U->if_read_ce(ap_var_for_const0);
    r_up_c_U->if_write_ce(ap_var_for_const0);
    r_up_c_U->if_din(Block_Mat_exit45_pro_U0_r_up_out_din);
    r_up_c_U->if_full_n(r_up_c_full_n);
    r_up_c_U->if_write(Block_Mat_exit45_pro_U0_r_up_out_write);
    r_up_c_U->if_dout(r_up_c_dout);
    r_up_c_U->if_empty_n(r_up_c_empty_n);
    r_up_c_U->if_read(hls_fire_dection_U0_r_up_read);
    g_low_c_U = new fifo_w32_d3_A("g_low_c_U");
    g_low_c_U->clk(ap_clk);
    g_low_c_U->reset(ap_rst_n_inv);
    g_low_c_U->if_read_ce(ap_var_for_const0);
    g_low_c_U->if_write_ce(ap_var_for_const0);
    g_low_c_U->if_din(Block_Mat_exit45_pro_U0_g_low_out_din);
    g_low_c_U->if_full_n(g_low_c_full_n);
    g_low_c_U->if_write(Block_Mat_exit45_pro_U0_g_low_out_write);
    g_low_c_U->if_dout(g_low_c_dout);
    g_low_c_U->if_empty_n(g_low_c_empty_n);
    g_low_c_U->if_read(hls_fire_dection_U0_g_low_read);
    g_up_c_U = new fifo_w32_d3_A("g_up_c_U");
    g_up_c_U->clk(ap_clk);
    g_up_c_U->reset(ap_rst_n_inv);
    g_up_c_U->if_read_ce(ap_var_for_const0);
    g_up_c_U->if_write_ce(ap_var_for_const0);
    g_up_c_U->if_din(Block_Mat_exit45_pro_U0_g_up_out_din);
    g_up_c_U->if_full_n(g_up_c_full_n);
    g_up_c_U->if_write(Block_Mat_exit45_pro_U0_g_up_out_write);
    g_up_c_U->if_dout(g_up_c_dout);
    g_up_c_U->if_empty_n(g_up_c_empty_n);
    g_up_c_U->if_read(hls_fire_dection_U0_g_up_read);
    b_low_c_U = new fifo_w32_d3_A("b_low_c_U");
    b_low_c_U->clk(ap_clk);
    b_low_c_U->reset(ap_rst_n_inv);
    b_low_c_U->if_read_ce(ap_var_for_const0);
    b_low_c_U->if_write_ce(ap_var_for_const0);
    b_low_c_U->if_din(Block_Mat_exit45_pro_U0_b_low_out_din);
    b_low_c_U->if_full_n(b_low_c_full_n);
    b_low_c_U->if_write(Block_Mat_exit45_pro_U0_b_low_out_write);
    b_low_c_U->if_dout(b_low_c_dout);
    b_low_c_U->if_empty_n(b_low_c_empty_n);
    b_low_c_U->if_read(hls_fire_dection_U0_b_low_read);
    b_up_c_U = new fifo_w32_d3_A("b_up_c_U");
    b_up_c_U->clk(ap_clk);
    b_up_c_U->reset(ap_rst_n_inv);
    b_up_c_U->if_read_ce(ap_var_for_const0);
    b_up_c_U->if_write_ce(ap_var_for_const0);
    b_up_c_U->if_din(Block_Mat_exit45_pro_U0_b_up_out_din);
    b_up_c_U->if_full_n(b_up_c_full_n);
    b_up_c_U->if_write(Block_Mat_exit45_pro_U0_b_up_out_write);
    b_up_c_U->if_dout(b_up_c_dout);
    b_up_c_U->if_empty_n(b_up_c_empty_n);
    b_up_c_U->if_read(hls_fire_dection_U0_b_up_read);
    img_0_rows_V_channel_U = new fifo_w32_d2_A("img_0_rows_V_channel_U");
    img_0_rows_V_channel_U->clk(ap_clk);
    img_0_rows_V_channel_U->reset(ap_rst_n_inv);
    img_0_rows_V_channel_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_channel_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_channel_U->if_din(Block_Mat_exit45_pro_U0_ap_return_0);
    img_0_rows_V_channel_U->if_full_n(img_0_rows_V_channel_full_n);
    img_0_rows_V_channel_U->if_write(ap_channel_done_img_0_rows_V_channel);
    img_0_rows_V_channel_U->if_dout(img_0_rows_V_channel_dout);
    img_0_rows_V_channel_U->if_empty_n(img_0_rows_V_channel_empty_n);
    img_0_rows_V_channel_U->if_read(AXIvideo2Mat_U0_ap_ready);
    img_0_cols_V_channel_U = new fifo_w32_d2_A("img_0_cols_V_channel_U");
    img_0_cols_V_channel_U->clk(ap_clk);
    img_0_cols_V_channel_U->reset(ap_rst_n_inv);
    img_0_cols_V_channel_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_channel_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_channel_U->if_din(Block_Mat_exit45_pro_U0_ap_return_1);
    img_0_cols_V_channel_U->if_full_n(img_0_cols_V_channel_full_n);
    img_0_cols_V_channel_U->if_write(ap_channel_done_img_0_cols_V_channel);
    img_0_cols_V_channel_U->if_dout(img_0_cols_V_channel_dout);
    img_0_cols_V_channel_U->if_empty_n(img_0_cols_V_channel_empty_n);
    img_0_cols_V_channel_U->if_read(AXIvideo2Mat_U0_ap_ready);
    img_0_data_stream_0_U = new fifo_w8_d2_A("img_0_data_stream_0_U");
    img_0_data_stream_0_U->clk(ap_clk);
    img_0_data_stream_0_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    img_0_data_stream_0_U->if_full_n(img_0_data_stream_0_full_n);
    img_0_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    img_0_data_stream_0_U->if_dout(img_0_data_stream_0_dout);
    img_0_data_stream_0_U->if_empty_n(img_0_data_stream_0_empty_n);
    img_0_data_stream_0_U->if_read(hls_fire_dection_U0_src_data_stream_0_V_read);
    img_0_data_stream_1_U = new fifo_w8_d2_A("img_0_data_stream_1_U");
    img_0_data_stream_1_U->clk(ap_clk);
    img_0_data_stream_1_U->reset(ap_rst_n_inv);
    img_0_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    img_0_data_stream_1_U->if_full_n(img_0_data_stream_1_full_n);
    img_0_data_stream_1_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    img_0_data_stream_1_U->if_dout(img_0_data_stream_1_dout);
    img_0_data_stream_1_U->if_empty_n(img_0_data_stream_1_empty_n);
    img_0_data_stream_1_U->if_read(hls_fire_dection_U0_src_data_stream_1_V_read);
    img_0_data_stream_2_U = new fifo_w8_d2_A("img_0_data_stream_2_U");
    img_0_data_stream_2_U->clk(ap_clk);
    img_0_data_stream_2_U->reset(ap_rst_n_inv);
    img_0_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    img_0_data_stream_2_U->if_full_n(img_0_data_stream_2_full_n);
    img_0_data_stream_2_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    img_0_data_stream_2_U->if_dout(img_0_data_stream_2_dout);
    img_0_data_stream_2_U->if_empty_n(img_0_data_stream_2_empty_n);
    img_0_data_stream_2_U->if_read(hls_fire_dection_U0_src_data_stream_2_V_read);
    img_1_data_stream_0_U = new fifo_w8_d2_A("img_1_data_stream_0_U");
    img_1_data_stream_0_U->clk(ap_clk);
    img_1_data_stream_0_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_din(hls_fire_dection_U0_dst_data_stream_0_V_din);
    img_1_data_stream_0_U->if_full_n(img_1_data_stream_0_full_n);
    img_1_data_stream_0_U->if_write(hls_fire_dection_U0_dst_data_stream_0_V_write);
    img_1_data_stream_0_U->if_dout(img_1_data_stream_0_dout);
    img_1_data_stream_0_U->if_empty_n(img_1_data_stream_0_empty_n);
    img_1_data_stream_0_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    img_1_data_stream_1_U = new fifo_w8_d2_A("img_1_data_stream_1_U");
    img_1_data_stream_1_U->clk(ap_clk);
    img_1_data_stream_1_U->reset(ap_rst_n_inv);
    img_1_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_1_U->if_din(hls_fire_dection_U0_dst_data_stream_1_V_din);
    img_1_data_stream_1_U->if_full_n(img_1_data_stream_1_full_n);
    img_1_data_stream_1_U->if_write(hls_fire_dection_U0_dst_data_stream_1_V_write);
    img_1_data_stream_1_U->if_dout(img_1_data_stream_1_dout);
    img_1_data_stream_1_U->if_empty_n(img_1_data_stream_1_empty_n);
    img_1_data_stream_1_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    img_1_data_stream_2_U = new fifo_w8_d2_A("img_1_data_stream_2_U");
    img_1_data_stream_2_U->clk(ap_clk);
    img_1_data_stream_2_U->reset(ap_rst_n_inv);
    img_1_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_2_U->if_din(hls_fire_dection_U0_dst_data_stream_2_V_din);
    img_1_data_stream_2_U->if_full_n(img_1_data_stream_2_full_n);
    img_1_data_stream_2_U->if_write(hls_fire_dection_U0_dst_data_stream_2_V_write);
    img_1_data_stream_2_U->if_dout(img_1_data_stream_2_dout);
    img_1_data_stream_2_U->if_empty_n(img_1_data_stream_2_empty_n);
    img_1_data_stream_2_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    start_for_hls_firg8j_U = new start_for_hls_firg8j("start_for_hls_firg8j_U");
    start_for_hls_firg8j_U->clk(ap_clk);
    start_for_hls_firg8j_U->reset(ap_rst_n_inv);
    start_for_hls_firg8j_U->if_read_ce(ap_var_for_const0);
    start_for_hls_firg8j_U->if_write_ce(ap_var_for_const0);
    start_for_hls_firg8j_U->if_din(start_for_hls_fire_dection_U0_din);
    start_for_hls_firg8j_U->if_full_n(start_for_hls_fire_dection_U0_full_n);
    start_for_hls_firg8j_U->if_write(Block_Mat_exit45_pro_U0_start_write);
    start_for_hls_firg8j_U->if_dout(start_for_hls_fire_dection_U0_dout);
    start_for_hls_firg8j_U->if_empty_n(start_for_hls_fire_dection_U0_empty_n);
    start_for_hls_firg8j_U->if_read(hls_fire_dection_U0_ap_ready);
    start_for_Mat2AXIhbi_U = new start_for_Mat2AXIhbi("start_for_Mat2AXIhbi_U");
    start_for_Mat2AXIhbi_U->clk(ap_clk);
    start_for_Mat2AXIhbi_U->reset(ap_rst_n_inv);
    start_for_Mat2AXIhbi_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXIhbi_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXIhbi_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIhbi_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIhbi_U->if_write(Block_Mat_exit45_pro_U0_start_write);
    start_for_Mat2AXIhbi_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIhbi_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIhbi_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);
    sensitive << ( img_0_rows_V_channel_empty_n );
    sensitive << ( img_0_cols_V_channel_empty_n );

    SC_METHOD(thread_AXIvideo2Mat_U0_start_full_n);

    SC_METHOD(thread_AXIvideo2Mat_U0_start_write);

    SC_METHOD(thread_Block_Mat_exit45_pro_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_img_0_cols_V_channel );
    sensitive << ( ap_sync_channel_write_img_0_rows_V_channel );

    SC_METHOD(thread_Block_Mat_exit45_pro_U0_ap_start);

    SC_METHOD(thread_Block_Mat_exit45_pro_U0_start_full_n);
    sensitive << ( start_for_hls_fire_dection_U0_full_n );
    sensitive << ( start_for_Mat2AXIvideo_U0_full_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_ap_channel_done_img_0_cols_V_channel);
    sensitive << ( Block_Mat_exit45_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_img_0_cols_V_channel );

    SC_METHOD(thread_ap_channel_done_img_0_rows_V_channel);
    sensitive << ( Block_Mat_exit45_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_img_0_rows_V_channel );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_channel_write_img_0_cols_V_channel);
    sensitive << ( ap_channel_done_img_0_cols_V_channel );
    sensitive << ( img_0_cols_V_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_img_0_cols_V_channel );

    SC_METHOD(thread_ap_sync_channel_write_img_0_rows_V_channel);
    sensitive << ( ap_channel_done_img_0_rows_V_channel );
    sensitive << ( img_0_rows_V_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_img_0_rows_V_channel );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_hls_fire_dection_U0_ap_continue);

    SC_METHOD(thread_hls_fire_dection_U0_ap_start);
    sensitive << ( start_for_hls_fire_dection_U0_empty_n );

    SC_METHOD(thread_hls_fire_dection_U0_start_full_n);

    SC_METHOD(thread_hls_fire_dection_U0_start_write);

    SC_METHOD(thread_input_r_TREADY);
    sensitive << ( AXIvideo2Mat_U0_input_r_TREADY );

    SC_METHOD(thread_output_r_TDATA);
    sensitive << ( Mat2AXIvideo_U0_output_r_TDATA );

    SC_METHOD(thread_output_r_TDEST);
    sensitive << ( Mat2AXIvideo_U0_output_r_TDEST );

    SC_METHOD(thread_output_r_TID);
    sensitive << ( Mat2AXIvideo_U0_output_r_TID );

    SC_METHOD(thread_output_r_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_output_r_TKEEP );

    SC_METHOD(thread_output_r_TLAST);
    sensitive << ( Mat2AXIvideo_U0_output_r_TLAST );

    SC_METHOD(thread_output_r_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_output_r_TSTRB );

    SC_METHOD(thread_output_r_TUSER);
    sensitive << ( Mat2AXIvideo_U0_output_r_TUSER );

    SC_METHOD(thread_output_r_TVALID);
    sensitive << ( Mat2AXIvideo_U0_output_r_TVALID );

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_hls_fire_dection_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_channel_write_img_0_cols_V_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_img_0_rows_V_channel = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fire_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, input_r_TDATA, "(port)input_r_TDATA");
    sc_trace(mVcdFile, input_r_TKEEP, "(port)input_r_TKEEP");
    sc_trace(mVcdFile, input_r_TSTRB, "(port)input_r_TSTRB");
    sc_trace(mVcdFile, input_r_TUSER, "(port)input_r_TUSER");
    sc_trace(mVcdFile, input_r_TLAST, "(port)input_r_TLAST");
    sc_trace(mVcdFile, input_r_TID, "(port)input_r_TID");
    sc_trace(mVcdFile, input_r_TDEST, "(port)input_r_TDEST");
    sc_trace(mVcdFile, output_r_TDATA, "(port)output_r_TDATA");
    sc_trace(mVcdFile, output_r_TKEEP, "(port)output_r_TKEEP");
    sc_trace(mVcdFile, output_r_TSTRB, "(port)output_r_TSTRB");
    sc_trace(mVcdFile, output_r_TUSER, "(port)output_r_TUSER");
    sc_trace(mVcdFile, output_r_TLAST, "(port)output_r_TLAST");
    sc_trace(mVcdFile, output_r_TID, "(port)output_r_TID");
    sc_trace(mVcdFile, output_r_TDEST, "(port)output_r_TDEST");
    sc_trace(mVcdFile, input_r_TVALID, "(port)input_r_TVALID");
    sc_trace(mVcdFile, input_r_TREADY, "(port)input_r_TREADY");
    sc_trace(mVcdFile, output_r_TVALID, "(port)output_r_TVALID");
    sc_trace(mVcdFile, output_r_TREADY, "(port)output_r_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, rows, "rows");
    sc_trace(mVcdFile, cols, "cols");
    sc_trace(mVcdFile, r_low, "r_low");
    sc_trace(mVcdFile, r_up, "r_up");
    sc_trace(mVcdFile, g_low, "g_low");
    sc_trace(mVcdFile, g_up, "g_up");
    sc_trace(mVcdFile, b_low, "b_low");
    sc_trace(mVcdFile, b_up, "b_up");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_start, "Block_Mat_exit45_pro_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_start_full_n, "Block_Mat_exit45_pro_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_done, "Block_Mat_exit45_pro_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_continue, "Block_Mat_exit45_pro_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_idle, "Block_Mat_exit45_pro_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_ready, "Block_Mat_exit45_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_start_out, "Block_Mat_exit45_pro_U0_start_out");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_start_write, "Block_Mat_exit45_pro_U0_start_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_rows_out_din, "Block_Mat_exit45_pro_U0_rows_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_rows_out_write, "Block_Mat_exit45_pro_U0_rows_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_cols_out_din, "Block_Mat_exit45_pro_U0_cols_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_cols_out_write, "Block_Mat_exit45_pro_U0_cols_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_rows_V_out_din, "Block_Mat_exit45_pro_U0_img_1_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_rows_V_out_write, "Block_Mat_exit45_pro_U0_img_1_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_cols_V_out_din, "Block_Mat_exit45_pro_U0_img_1_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_cols_V_out_write, "Block_Mat_exit45_pro_U0_img_1_cols_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_r_low_out_din, "Block_Mat_exit45_pro_U0_r_low_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_r_low_out_write, "Block_Mat_exit45_pro_U0_r_low_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_r_up_out_din, "Block_Mat_exit45_pro_U0_r_up_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_r_up_out_write, "Block_Mat_exit45_pro_U0_r_up_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_g_low_out_din, "Block_Mat_exit45_pro_U0_g_low_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_g_low_out_write, "Block_Mat_exit45_pro_U0_g_low_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_g_up_out_din, "Block_Mat_exit45_pro_U0_g_up_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_g_up_out_write, "Block_Mat_exit45_pro_U0_g_up_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_b_low_out_din, "Block_Mat_exit45_pro_U0_b_low_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_b_low_out_write, "Block_Mat_exit45_pro_U0_b_low_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_b_up_out_din, "Block_Mat_exit45_pro_U0_b_up_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_b_up_out_write, "Block_Mat_exit45_pro_U0_b_up_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_return_0, "Block_Mat_exit45_pro_U0_ap_return_0");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_return_1, "Block_Mat_exit45_pro_U0_ap_return_1");
    sc_trace(mVcdFile, ap_channel_done_img_0_cols_V_channel, "ap_channel_done_img_0_cols_V_channel");
    sc_trace(mVcdFile, img_0_cols_V_channel_full_n, "img_0_cols_V_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_img_0_cols_V_channel, "ap_sync_reg_channel_write_img_0_cols_V_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_img_0_cols_V_channel, "ap_sync_channel_write_img_0_cols_V_channel");
    sc_trace(mVcdFile, ap_channel_done_img_0_rows_V_channel, "ap_channel_done_img_0_rows_V_channel");
    sc_trace(mVcdFile, img_0_rows_V_channel_full_n, "img_0_rows_V_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_img_0_rows_V_channel, "ap_sync_reg_channel_write_img_0_rows_V_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_img_0_rows_V_channel, "ap_sync_channel_write_img_0_rows_V_channel");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_input_r_TREADY, "AXIvideo2Mat_U0_input_r_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, hls_fire_dection_U0_ap_start, "hls_fire_dection_U0_ap_start");
    sc_trace(mVcdFile, hls_fire_dection_U0_ap_done, "hls_fire_dection_U0_ap_done");
    sc_trace(mVcdFile, hls_fire_dection_U0_ap_continue, "hls_fire_dection_U0_ap_continue");
    sc_trace(mVcdFile, hls_fire_dection_U0_ap_idle, "hls_fire_dection_U0_ap_idle");
    sc_trace(mVcdFile, hls_fire_dection_U0_ap_ready, "hls_fire_dection_U0_ap_ready");
    sc_trace(mVcdFile, hls_fire_dection_U0_src_data_stream_0_V_read, "hls_fire_dection_U0_src_data_stream_0_V_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_src_data_stream_1_V_read, "hls_fire_dection_U0_src_data_stream_1_V_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_src_data_stream_2_V_read, "hls_fire_dection_U0_src_data_stream_2_V_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_dst_data_stream_0_V_din, "hls_fire_dection_U0_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, hls_fire_dection_U0_dst_data_stream_0_V_write, "hls_fire_dection_U0_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, hls_fire_dection_U0_dst_data_stream_1_V_din, "hls_fire_dection_U0_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, hls_fire_dection_U0_dst_data_stream_1_V_write, "hls_fire_dection_U0_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, hls_fire_dection_U0_dst_data_stream_2_V_din, "hls_fire_dection_U0_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, hls_fire_dection_U0_dst_data_stream_2_V_write, "hls_fire_dection_U0_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, hls_fire_dection_U0_rows_read, "hls_fire_dection_U0_rows_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_cols_read, "hls_fire_dection_U0_cols_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_r_low_read, "hls_fire_dection_U0_r_low_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_r_up_read, "hls_fire_dection_U0_r_up_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_g_low_read, "hls_fire_dection_U0_g_low_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_g_up_read, "hls_fire_dection_U0_g_up_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_b_low_read, "hls_fire_dection_U0_b_low_read");
    sc_trace(mVcdFile, hls_fire_dection_U0_b_up_read, "hls_fire_dection_U0_b_up_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_rows_V_read, "Mat2AXIvideo_U0_img_rows_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_cols_V_read, "Mat2AXIvideo_U0_img_cols_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TDATA, "Mat2AXIvideo_U0_output_r_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TVALID, "Mat2AXIvideo_U0_output_r_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TKEEP, "Mat2AXIvideo_U0_output_r_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TSTRB, "Mat2AXIvideo_U0_output_r_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TUSER, "Mat2AXIvideo_U0_output_r_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TLAST, "Mat2AXIvideo_U0_output_r_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TID, "Mat2AXIvideo_U0_output_r_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_output_r_TDEST, "Mat2AXIvideo_U0_output_r_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, rows_c_full_n, "rows_c_full_n");
    sc_trace(mVcdFile, rows_c_dout, "rows_c_dout");
    sc_trace(mVcdFile, rows_c_empty_n, "rows_c_empty_n");
    sc_trace(mVcdFile, cols_c_full_n, "cols_c_full_n");
    sc_trace(mVcdFile, cols_c_dout, "cols_c_dout");
    sc_trace(mVcdFile, cols_c_empty_n, "cols_c_empty_n");
    sc_trace(mVcdFile, img_1_rows_V_c_full_n, "img_1_rows_V_c_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c_dout, "img_1_rows_V_c_dout");
    sc_trace(mVcdFile, img_1_rows_V_c_empty_n, "img_1_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c_full_n, "img_1_cols_V_c_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c_dout, "img_1_cols_V_c_dout");
    sc_trace(mVcdFile, img_1_cols_V_c_empty_n, "img_1_cols_V_c_empty_n");
    sc_trace(mVcdFile, r_low_c_full_n, "r_low_c_full_n");
    sc_trace(mVcdFile, r_low_c_dout, "r_low_c_dout");
    sc_trace(mVcdFile, r_low_c_empty_n, "r_low_c_empty_n");
    sc_trace(mVcdFile, r_up_c_full_n, "r_up_c_full_n");
    sc_trace(mVcdFile, r_up_c_dout, "r_up_c_dout");
    sc_trace(mVcdFile, r_up_c_empty_n, "r_up_c_empty_n");
    sc_trace(mVcdFile, g_low_c_full_n, "g_low_c_full_n");
    sc_trace(mVcdFile, g_low_c_dout, "g_low_c_dout");
    sc_trace(mVcdFile, g_low_c_empty_n, "g_low_c_empty_n");
    sc_trace(mVcdFile, g_up_c_full_n, "g_up_c_full_n");
    sc_trace(mVcdFile, g_up_c_dout, "g_up_c_dout");
    sc_trace(mVcdFile, g_up_c_empty_n, "g_up_c_empty_n");
    sc_trace(mVcdFile, b_low_c_full_n, "b_low_c_full_n");
    sc_trace(mVcdFile, b_low_c_dout, "b_low_c_dout");
    sc_trace(mVcdFile, b_low_c_empty_n, "b_low_c_empty_n");
    sc_trace(mVcdFile, b_up_c_full_n, "b_up_c_full_n");
    sc_trace(mVcdFile, b_up_c_dout, "b_up_c_dout");
    sc_trace(mVcdFile, b_up_c_empty_n, "b_up_c_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_channel_dout, "img_0_rows_V_channel_dout");
    sc_trace(mVcdFile, img_0_rows_V_channel_empty_n, "img_0_rows_V_channel_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_channel_dout, "img_0_cols_V_channel_dout");
    sc_trace(mVcdFile, img_0_cols_V_channel_empty_n, "img_0_cols_V_channel_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_full_n, "img_0_data_stream_0_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_dout, "img_0_data_stream_0_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_empty_n, "img_0_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_full_n, "img_0_data_stream_1_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_dout, "img_0_data_stream_1_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_empty_n, "img_0_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_full_n, "img_0_data_stream_2_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_dout, "img_0_data_stream_2_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_empty_n, "img_0_data_stream_2_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_full_n, "img_1_data_stream_0_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_dout, "img_1_data_stream_0_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_empty_n, "img_1_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_1_full_n, "img_1_data_stream_1_full_n");
    sc_trace(mVcdFile, img_1_data_stream_1_dout, "img_1_data_stream_1_dout");
    sc_trace(mVcdFile, img_1_data_stream_1_empty_n, "img_1_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_2_full_n, "img_1_data_stream_2_full_n");
    sc_trace(mVcdFile, img_1_data_stream_2_dout, "img_1_data_stream_2_dout");
    sc_trace(mVcdFile, img_1_data_stream_2_empty_n, "img_1_data_stream_2_empty_n");
    sc_trace(mVcdFile, start_for_hls_fire_dection_U0_din, "start_for_hls_fire_dection_U0_din");
    sc_trace(mVcdFile, start_for_hls_fire_dection_U0_full_n, "start_for_hls_fire_dection_U0_full_n");
    sc_trace(mVcdFile, start_for_hls_fire_dection_U0_dout, "start_for_hls_fire_dection_U0_dout");
    sc_trace(mVcdFile, start_for_hls_fire_dection_U0_empty_n, "start_for_hls_fire_dection_U0_empty_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_full_n, "AXIvideo2Mat_U0_start_full_n");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, hls_fire_dection_U0_start_full_n, "hls_fire_dection_U0_start_full_n");
    sc_trace(mVcdFile, hls_fire_dection_U0_start_write, "hls_fire_dection_U0_start_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("fire.hdltvin.dat");
    mHdltvoutHandle.open("fire.hdltvout.dat");
}

fire::~fire() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete fire_AXILiteS_s_axi_U;
    delete Block_Mat_exit45_pro_U0;
    delete AXIvideo2Mat_U0;
    delete hls_fire_dection_U0;
    delete Mat2AXIvideo_U0;
    delete rows_c_U;
    delete cols_c_U;
    delete img_1_rows_V_c_U;
    delete img_1_cols_V_c_U;
    delete r_low_c_U;
    delete r_up_c_U;
    delete g_low_c_U;
    delete g_up_c_U;
    delete b_low_c_U;
    delete b_up_c_U;
    delete img_0_rows_V_channel_U;
    delete img_0_cols_V_channel_U;
    delete img_0_data_stream_0_U;
    delete img_0_data_stream_1_U;
    delete img_0_data_stream_2_U;
    delete img_1_data_stream_0_U;
    delete img_1_data_stream_1_U;
    delete img_1_data_stream_2_U;
    delete start_for_hls_firg8j_U;
    delete start_for_Mat2AXIhbi_U;
}

void fire::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fire::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_img_0_cols_V_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit45_pro_U0_ap_done.read() & 
             Block_Mat_exit45_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_img_0_cols_V_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_img_0_cols_V_channel = ap_sync_channel_write_img_0_cols_V_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_img_0_rows_V_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit45_pro_U0_ap_done.read() & 
             Block_Mat_exit45_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_img_0_rows_V_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_img_0_rows_V_channel = ap_sync_channel_write_img_0_rows_V_channel.read();
        }
    }
}

void fire::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void fire::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = (img_0_rows_V_channel_empty_n.read() & img_0_cols_V_channel_empty_n.read());
}

void fire::thread_AXIvideo2Mat_U0_start_full_n() {
    AXIvideo2Mat_U0_start_full_n = ap_const_logic_1;
}

void fire::thread_AXIvideo2Mat_U0_start_write() {
    AXIvideo2Mat_U0_start_write = ap_const_logic_0;
}

void fire::thread_Block_Mat_exit45_pro_U0_ap_continue() {
    Block_Mat_exit45_pro_U0_ap_continue = (ap_sync_channel_write_img_0_cols_V_channel.read() & ap_sync_channel_write_img_0_rows_V_channel.read());
}

void fire::thread_Block_Mat_exit45_pro_U0_ap_start() {
    Block_Mat_exit45_pro_U0_ap_start = ap_const_logic_1;
}

void fire::thread_Block_Mat_exit45_pro_U0_start_full_n() {
    Block_Mat_exit45_pro_U0_start_full_n = (start_for_hls_fire_dection_U0_full_n.read() & start_for_Mat2AXIvideo_U0_full_n.read());
}

void fire::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void fire::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void fire::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void fire::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void fire::thread_ap_channel_done_img_0_cols_V_channel() {
    ap_channel_done_img_0_cols_V_channel = (Block_Mat_exit45_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_img_0_cols_V_channel.read() ^ 
  ap_const_logic_1));
}

void fire::thread_ap_channel_done_img_0_rows_V_channel() {
    ap_channel_done_img_0_rows_V_channel = (Block_Mat_exit45_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_img_0_rows_V_channel.read() ^ 
  ap_const_logic_1));
}

void fire::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void fire::thread_ap_sync_channel_write_img_0_cols_V_channel() {
    ap_sync_channel_write_img_0_cols_V_channel = ((ap_channel_done_img_0_cols_V_channel.read() & 
  img_0_cols_V_channel_full_n.read()) | ap_sync_reg_channel_write_img_0_cols_V_channel.read());
}

void fire::thread_ap_sync_channel_write_img_0_rows_V_channel() {
    ap_sync_channel_write_img_0_rows_V_channel = ((ap_channel_done_img_0_rows_V_channel.read() & 
  img_0_rows_V_channel_full_n.read()) | ap_sync_reg_channel_write_img_0_rows_V_channel.read());
}

void fire::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void fire::thread_hls_fire_dection_U0_ap_continue() {
    hls_fire_dection_U0_ap_continue = ap_const_logic_1;
}

void fire::thread_hls_fire_dection_U0_ap_start() {
    hls_fire_dection_U0_ap_start = start_for_hls_fire_dection_U0_empty_n.read();
}

void fire::thread_hls_fire_dection_U0_start_full_n() {
    hls_fire_dection_U0_start_full_n = ap_const_logic_1;
}

void fire::thread_hls_fire_dection_U0_start_write() {
    hls_fire_dection_U0_start_write = ap_const_logic_0;
}

void fire::thread_input_r_TREADY() {
    input_r_TREADY = AXIvideo2Mat_U0_input_r_TREADY.read();
}

void fire::thread_output_r_TDATA() {
    output_r_TDATA = Mat2AXIvideo_U0_output_r_TDATA.read();
}

void fire::thread_output_r_TDEST() {
    output_r_TDEST = Mat2AXIvideo_U0_output_r_TDEST.read();
}

void fire::thread_output_r_TID() {
    output_r_TID = Mat2AXIvideo_U0_output_r_TID.read();
}

void fire::thread_output_r_TKEEP() {
    output_r_TKEEP = Mat2AXIvideo_U0_output_r_TKEEP.read();
}

void fire::thread_output_r_TLAST() {
    output_r_TLAST = Mat2AXIvideo_U0_output_r_TLAST.read();
}

void fire::thread_output_r_TSTRB() {
    output_r_TSTRB = Mat2AXIvideo_U0_output_r_TSTRB.read();
}

void fire::thread_output_r_TUSER() {
    output_r_TUSER = Mat2AXIvideo_U0_output_r_TUSER.read();
}

void fire::thread_output_r_TVALID() {
    output_r_TVALID = Mat2AXIvideo_U0_output_r_TVALID.read();
}

void fire::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fire::thread_start_for_hls_fire_dection_U0_din() {
    start_for_hls_fire_dection_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void fire::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TDATA\" :  \"" << input_r_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TKEEP\" :  \"" << input_r_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TSTRB\" :  \"" << input_r_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TUSER\" :  \"" << input_r_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TLAST\" :  \"" << input_r_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TID\" :  \"" << input_r_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TDEST\" :  \"" << input_r_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TDATA\" :  \"" << output_r_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TKEEP\" :  \"" << output_r_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TSTRB\" :  \"" << output_r_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TUSER\" :  \"" << output_r_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TLAST\" :  \"" << output_r_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TID\" :  \"" << output_r_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TDEST\" :  \"" << output_r_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_TVALID\" :  \"" << input_r_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_TREADY\" :  \"" << input_r_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_TVALID\" :  \"" << output_r_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_r_TREADY\" :  \"" << output_r_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

