set_property PACKAGE_PIN U20 [get_ports cmos_pclk]
set_property PACKAGE_PIN N18 [get_ports cmos_href]
set_property PACKAGE_PIN T20 [get_ports cmos_vsync]
set_property PACKAGE_PIN N20 [get_ports cmos_rst_n]
set_property PACKAGE_PIN V16 [get_ports cmos_sda]
set_property PACKAGE_PIN T16 [get_ports cmos_scl]

set_property PACKAGE_PIN R16 [get_ports {cmos_data[7]}]
set_property PACKAGE_PIN U18 [get_ports {cmos_data[6]}]
set_property PACKAGE_PIN P19 [get_ports {cmos_data[5]}]
set_property PACKAGE_PIN R18 [get_ports {cmos_data[4]}]
set_property PACKAGE_PIN T17 [get_ports {cmos_data[3]}]
set_property PACKAGE_PIN R17 [get_ports {cmos_data[2]}]
set_property PACKAGE_PIN W16 [get_ports {cmos_data[1]}]
set_property PACKAGE_PIN P18 [get_ports {cmos_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cmos_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_href]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[7]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos_pclk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_oen[0]}]
set_property PACKAGE_PIN F17 [get_ports {hdmi_oen[0]}]


set_property PACKAGE_PIN D19 [get_ports {TMDS_data_p[0]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS_data_p[1]}]
set_property PACKAGE_PIN B19 [get_ports {TMDS_data_p[2]}]
set_property PACKAGE_PIN H16 [get_ports TMDS_clk_p]

set_property PULLUP true [get_ports cmos_scl]
set_property PULLUP true [get_ports cmos_sda]
